language: ruby

rvm:
  - 2.4.1

cache: bundler

services:
  - mysql
  - postgresql

before_install:
  - mysql -e 'CREATE DATABASE graphql_analyzer_test;'
  - psql -c 'CREATE DATABASE graphql_analyzer_test;' -U postgres

notifications:
  email:
    on_success: never
    on_failure: always