language: ruby

rvm:
  - 2.4.1

cache: bundler

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE graphql_analyzer_test;'

notifications:
  email:
    on_success: never
    on_failure: always