default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: spec/support/active_record/db/development.sqlite3

test:
  <<: *default
  database: ':memory:'

production:
  <<: *default
  database: spec/support/active_record/db/production.sqlite3
